# Site settings
title:       Michał Płachta's Blog
author:      Michał Płachta
email:       miciek@gmail.com
description: "Blog about software engineering. I write about technical and organisational problems and try to come up with solutions based on experiments and research."
baseurl:     ""
url:         "https://michalplachta.com"
date_format: "%b %-d, %Y"
future: false
header_pages:
 - about.md
 - talks.md
 - book.md
 - workshops.md
 - contact.html

# Google services
google_verification:

# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: michalplachta

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Social icons
github_username: miciek
reddit_username:
bitbucket_username:
stackoverflow_id:
twitter_username: miciek
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'Sending...'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
